[bot] # basic bot information
token = "DISCORD TOKEN HERE"
app_id = 1234567890
# prefix for commands
cmd_prefix = "."

[image] # Image options
# quality of .webp images uploaded to discord
webp_quality = 80
